Add partially finished quest information for Kenneth Haight and Nepheli Loux
Gobluebro/Elden-Ring-Checklist pull request #2
Opened 2022-03-20 17:56 UTC by clicksilver

Kenneth and Nepheli's questlines were updated in v1.03 to have added steps but those have still not yet been determined fully. I added only those steps that existed before v1.03 for posterity.

2022-03-20 17:58 UTC, clicksilver commented
This should address this issue here: https://github.com/Gobluebro/Elden-Ring-Checklist/issues/1

2022-03-20 19:33 UTC, clicksilver commented
rebased to fix the errors in build

2022-03-20 20:39 UTC, Gobluebro requested changes
This looks good. Thank you for your hard work. I have added some changes that I think make these requirements a little more clear.

A side note:
I'm not sure if talking to Gideon Ofnir is required to progress some of Nepheli's questline or not. I might add it after this pull request goes through though.

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +        description: "Visit Roundtable Hold and talk to Nepheli. Receive the Arsenal Talisman.",
```suggestion
        id: "",
        description: "Talk to Nepheli at Roundtable Hold grace. Receive the Arsenal Talisman.",
```

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +      },
I'd say that since we care about this quest line. We should always pursue the ending that benefits the user. Since giving Nepheli the potion ruins the quest line we should warn the user not to give this potion to her at any point. I believe giving the potion to her father or the Dung Eater is the better option since they do not ruin this story. And giving it to the dung eater will provide you with a puppet in Seluvis's quest line. So that benefits the user who values collecting everything in the game.

I will probably make an optional "notes" property to warn users of giving the potion to her.

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +        description: "Meet Nepheli at the Village of the Albinaurics.",
```suggestion
        id: "",
        description: "Meet Nepheli under the bridge at the Village of the Albinaurics.",
```

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +      },
```suggestion
      {
        id: "",
        description: "Talk to Nepheli at the Roundtable Hold grace.",
      },
```

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +      },
```suggestion
        id: "",
        description: "Explore the Church of Anticipation, and find the Stormhawk King.",
      },
```

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +        description: "To Be Determined ...",
I'd say it's worth to include what is known about this quest line after patch 1.03. 

```suggestion
        id: "",
        description: "Talk to Nepheli at the Stormveil Castle throne room.",
```

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +        description: "To Be Determined ...",
I'd say it's worth to include what is known about this quest line after patch 1.03.
```suggestion
        id: "",
        description: "Once you have completed Nepheli's questline, talk to Kenneth at the Stormveil Castle throne room.",
```

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +    name: "Kenneth Haight (Incomplete)",
I've added what information is currently known about this questline. So I'd leave this without the incomplete line. If anything else is found about this, then it can be added later.

```suggestion
    id: "",
    name: "Kenneth Haight",
```

2022-03-20 20:39 UTC, Gobluebro commented on data/quests.ts
> +    name: "Nepheli Loux (Incomplete)",
I've added what information is currently known about this questline. So I'd leave this without the incomplete line. If anything else is found about this, then it can be added later.
```suggestion
    id: "",
    name: "Nepheli Loux",
```

2022-03-20 20:49 UTC, Gobluebro commented on data/quests.ts
> +        description: "Meet Nepheli Loux in Stormveil Castle, nearby the Secluded Corridoor site of grace.",
maybe "before" sounds better than near.

2022-03-21 19:11 UTC, clicksilver commented on data/quests.ts
> +      },
I believe the Ashes are necessary item here. Is the Stormhawk King another NPC, or is it the correct name of the item?

2022-03-21 19:14 UTC, clicksilver commented on data/quests.ts
> +      },
Makes sense. We can just put the choice aspect under Seluvis' chain anyway.

2022-03-21 20:57 UTC, Gobluebro commented on data/quests.ts
> +        description: "Talk to Kenneth at his first location. Receive a reward.",
I don't believe the receiving of an item is really important information unless it 

1. Is the last thing you talk about with the NPC.
2. Is an important quest item required later.

Since it is neither of those, I chose to put the dialogue option since it is the last thing you talk to him about. I try to keep all things related to one area in the same requirement but I don't like them getting too long.

2022-03-21 20:58 UTC, Gobluebro commented on data/quests.ts
> +      },
[It is the correct name of the item](https://eldenring.wiki.fextralife.com/The+Stormhawk+King)

2022-03-24 02:10 UTC, merged